name: CI
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # TODO add dependency caching
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - run: yarn --frozen-lockfile
        working-directory: checkers-client
      - run: yarn build
        working-directory: checkers-client
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: checkers-client/public
