name: CI
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./checkers-client
    steps:
      # TODO add dependency caching
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn deploy
