name: CI
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # TODO add dependency caching
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - working-directory: $GITHUB_WORKSPACE/checkers-client
        run: yarn install --frozen-lockfile
      - working-directory: $GITHUB_WORKSPACE/checkers-client
        run: yarn deploy
